services:
  {{ Self::service_name() }}:
    image: samply/beam-proxy
    environment:
      BROKER_URL: {{ T::broker_url() }}
      PROXY_ID: {{ proxy_id }}
      {% for (app_name, secret) in app_keys -%}
        APP_{{ app_name }}_KEY: "{{secret}}"
      {% endfor %}
