services:
  {{ Self::service_name() }}:
    image: docker.verbis.dkfz.de/cache/samply/beam-connect:develop
    environment:
      PROXY_URL: {{ beam.url }}
      TLS_CA_CERTIFICATES_DIR: /trusted_ca_certs
      APP_ID: {{ beam.id }}
      PROXY_APIKEY: {{ beam.secret }}
      DISCOVERY_URL: "./central-targets"
      LOCAL_TARGETS_FILE: "./local-targets"
      NO_AUTH: "true"
    volumes:
      - {{ trusted_ca_certs.display() }}:/trusted_ca_certs/:ro
    configs:
      - local-targets
      - central-targets

configs:
  local-targets:
    content: |
      {{ serde_json::to_string_pretty(&local_targets)?|indent(6) }}
  central-targets:
    content: |
      {{ format_central_targets()?|indent(6) }}
