{% let name = Self::service_name() %}
services:
  {{ name }}:
    image: docker.verbis.dkfz.de/cache/samply/blaze:latest
    environment:
      BASE_URL: {{ Self::get_url().to_string().trim_end_matches('/') }}
      ENFORCE_REFERENTIAL_INTEGRITY: "false"
    volumes:
      - "{{ name }}-data:/app/data"
    {% if let Some(traefik_conf) = traefik_conf -%}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.{{ name }}.rule=PathPrefix(`{{ traefik_conf.path }}`)"
      - "traefik.http.middlewares.{{ name }}_strip.stripprefix.prefixes={{ traefik_conf.path }}"
      - "traefik.http.services.{{ name }}.loadbalancer.server.port=8080"
      - "traefik.http.routers.{{ name }}.middlewares={{ name }}_strip,{{ traefik_conf.middleware_and_user_name }}"
      - "traefik.http.routers.{{ name }}.tls=true"
    {%- endif %}

volumes:
  {{ name }}-data:
