{% let name = Self::service_name() %}
{% let data_volume = format!("{}-data", name) %}
services:
  {{ name }}:
    image: docker.verbis.dkfz.de/cache/samply/blaze:latest
    environment:
      BASE_URL: {{ Self::get_url().to_string().trim_end_matches('/') }}
      ENFORCE_REFERENTIAL_INTEGRITY: "false"
    {%- if let Some(heap_size) = tuning.heap_size %}
      JAVA_TOOL_OPTIONS: "-Xmx{{ heap_size }}"
    {%- endif %}
      DB_BLOCK_CACHE_SIZE: "{{ tuning.block_cache_size }}"
    {%- if tuning.cql_expr_cache_size > 0 %}
      CQL_EXPR_CACHE_SIZE: "{{ tuning.cql_expr_cache_size }}"
    {%- endif %}
    {%- if let Some(ratio) = tuning.resource_cache_size_ratio %}
      DB_RESOURCE_CACHE_SIZE_RATIO: "{{ ratio }}"
    {%- endif %}
    volumes:
      - "{{ data_volume }}:/app/data"
    {% if let Some(traefik_conf) = traefik_conf -%}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.{{ name }}.rule=PathPrefix(`{{ traefik_conf.path }}`)"
      - "traefik.http.middlewares.{{ name }}_strip.stripprefix.prefixes={{ traefik_conf.path }}"
      - "traefik.http.services.{{ name }}.loadbalancer.server.port=8080"
      - "traefik.http.routers.{{ name }}.middlewares={{ name }}_strip,{{ traefik_conf.middleware_and_user_name }}"
      - "traefik.http.routers.{{ name }}.tls=true"
    {%- endif %}

volumes:
  {{ data_volume|make_volume }}
