{% let name = Self::service_name() %}
services:
  {{ name }}:
    image: docker.verbis.dkfz.de/cache/samply/blaze:latest
    environment:
      BASE_URL: {{ get_url() }}
    volumes:
      - "{{ name }}-data:/app/data"
    {% if let Some(traefik_conf) = traefik_conf -%}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.{{ name }}.rule=PathPrefix(`{{ traefik_conf.path }}`)"
      - "traefik.http.middlewares.{{ name }}_strip.stripprefix.prefixes={{ traefik_conf.path }}"
      - "traefik.http.services.{{ name }}.loadbalancer.server.port=8080"
      - "traefik.http.routers.{{ name }}.middlewares={{ name }}_strip,blaze"
      - "traefik.http.routers.{{ name }}.tls=true"
    {%- endif %}
  
volumes:
  {{ name }}-data: