#!/usr/bin/env bash
set -e
set -o pipefail

{%- let config_dir = conf.path|path %}
{%- let priv_key_file = conf.path.join(format!("pki/{}.priv.pem", self.conf.site_id)) %}

# Ensure the script is running in memory to avoid issues with self modification on update
[ "$LOADED" = 1 ] || LOADED=1 exec bash <(cat "$0") "$@"
cd {{ config_dir }}

COMPOSE_FILES="$(ls services | awk '{print " -f services/" $0}')"
[ -e ./docker-compose.override.yml ] && COMPOSE_FILES+=" -f docker-compose.override.yml"

main() {
    case "$1" in
        install)
            [ "$(id -u)" -ne 0 ] && echo "Install command must be run as root." && exit 1
            useradd -M -g docker -N bridgehead &>/dev/null || echo "Using existing user bridgehead."
            chown -R bridgehead:docker .
            chmod -R g+sw .
            sudo -u bridgehead git init -b main
            git config --global --add safe.directory {{ config_dir }}
            git config --local user.email "bridgehead@samply.de"
            git config --local user.name "Bridgehead"
            {%- if let Some(proxy_url) = conf.https_proxy_url %}
            git config --local http.proxy {{ proxy_url }}
            git config --local https.proxy {{ proxy_url }}
            {%- endif %}
            if ! systemctl list-units &> /dev/null; then
                echo "Systemd is not active. Skipping systemd setup."
                sudo -u bridgehead TAG=$TAG ./bridgehead update
            else
                install_systemd
            fi
            {%- if beam_networks.is_empty() %}
            echo "Installation complete."
            echo "You may start the bridgehead service with 'systemctl start bridgehead' or '{{ config_dir }}/bridgehead compose up' now."
            {%- else %}
            if [ -e {{ priv_key_file.display() }} ]; then
                echo "Private key already exists. Skipping enrollment."
                echo "If you want to re-enroll or changed the configuration and are now included in a new beam network run 'sudo {{ config_dir }}/bridgehead enroll'."
                echo "Installation complete."
            else
                enroll
            fi
            {%- endif %}
            ;;
        logs)
            shift
            exec journalctl -u bridgehead -u bridgehead-update -a $@
            ;;
        compose)
            {%- if !beam_networks.is_empty() %}
            if [ ! -f {{ priv_key_file.display() }} ]; then
                echo "Beam private key not found. Please run 'sudo {{ config_dir }}/bridgehead enroll' first."
                exit 1
            fi
            {%- endif %}
            shift
            exec docker compose -p bridgehead --env-file .env $COMPOSE_FILES -f docker-image.lock.yml $@
            ;;
        {%- if !beam_networks.is_empty() %}
        enroll)
            [ "$(id -u)" -ne 0 ] && echo "Enroll must be run as root." && exit 1
            enroll
            ;;
        {%- endif %}
        update)
            update
            ;;
        *)
            echo "Unknown bridgehead command '$@'"
            exit 1
            ;;
    esac
}

update() {
    env_hash=$(sha1sum .env | awk '{print $1}')
    services_hash=$(sha1sum services/* | awk '{print $1}')
    image_hashes=$(sha1sum docker-image.lock.yml | awk '{print $1}')
    # Check if the repo is dirty and if it is print a warning and stash the changes
    changes=$(git status --porcelain)
    if [ -n "$changes" ]; then
        echo -e "Warning: Repository is dirty:\n$changes\nStashing changes..."
        git add . && git stash || true
    fi
    # TODO: Check if the bridgehead script changed and if so rerun
    # TODO: Read tag from config
    docker pull samply/rusthead:${TAG:-latest} &>/dev/null || echo "Failed to pull latest rusthead image. Using latest local image."
    docker run --rm \
        -v {{ config_dir }}:{{ config_dir }} \
        -e BRIDGEHEAD_CONFIG_PATH={{ config_dir }} \
        -u "$(id -u bridgehead):$(id -g bridgehead)" \
        samply/rusthead:${TAG:-latest} update
    docker image prune -f
    # TODO: Check if we have any services
    new_compose_files="$(ls services | awk '{print " -f services/" $0}')"
    [ -e ./docker-compose.override.yml ] && new_compose_files+=" -f docker-compose.override.yml"
    docker compose --env-file .env $new_compose_files pull
    docker compose --env-file .env $new_compose_files config --lock-image-digests > docker-image.lock.yml
    env_changed=$([ "$env_hash" != "$(sha1sum .env | awk '{print $1}')" ] && echo true || echo false)
    services_changed=$([ "$services_hash" != "$(sha1sum services/* | awk '{print $1}')" ] && echo true || echo false)
    images_changed=$([ "$image_hashes" != "$(sha1sum docker-image.lock.yml | awk '{print $1}')" ] && echo true || echo false)

    changes=$(git status --porcelain)
    if [ "$env_changed" = true ] || [ "$services_changed" = true ] || [ "$images_changed" = true ] || [ -n "$changes" ]; then
        msg="Update completed. Changes detected in:"
        [ "$env_changed" = true ] && msg+="\n  - Environment configuration"
        [ "$services_changed" = true ] && msg+="\n  - Services configuration"
        [ "$images_changed" = true ] && msg+="\n  - Docker images"
        [ -n "$changes" ] && msg+="\nChanges: \n$changes"
        git add .
        echo -e "Updated bridgehead\n\n$msg" | git commit -F -
    else
        echo "Update completed. No changes detected - everything is up to date."
    fi
}

{%- if !beam_networks.is_empty() %}
enroll() {
    do_enroll() {
        echo "Enrolling {{ conf.site_id }}.$1"
        docker run --rm \
            -v {{ config_dir }}/pki:{{ config_dir }}/pki \
            docker.verbis.dkfz.de/cache/samply/beam-enroll:latest \
            --output-file {{ priv_key_file.display() }} \
            --proxy-id {{ conf.site_id }}.$1
        chmod 600 {{ priv_key_file.display() }}
    }
    {% for broker in beam_networks -%}
        do_enroll {{ broker }}
    {%- endfor %}
    echo "After getting the csr{{ beam_networks.len()|pluralize }} enrolled you may start the bridgehead service with 'systemctl start bridgehead'."
}
{%- endif %}

install_systemd() {
    cat <<EOF > /etc/systemd/system/bridgehead.service
[Unit]
Description=Bridgehead Service
Requires=docker.service

[Service]
ExecStart={{ config_dir }}/bridgehead compose up
Restart=always
User=bridgehead
Group=docker

[Install]
WantedBy=multi-user.target
EOF
    cat <<EOF > /etc/systemd/system/bridgehead-update.service
[Unit]
Description=Bridgehead Update Service
Requires=docker.service

[Service]
ExecStart={{ config_dir }}/bridgehead update
User=bridgehead
Group=docker
EOF
    cat <<EOF > /etc/systemd/system/bridgehead-update.timer
[Unit]
Description=Daily Updates at 6am of Bridgehead

[Timer]
OnCalendar=*-*-* 06:00:00
Persistent=true

[Install]
WantedBy=basic.target
EOF
    systemctl daemon-reload
    systemctl start bridgehead-update.service
    echo "Enabling autostart of bridgehead.service"
    systemctl enable bridgehead.service
    echo "Enabling auto-updates for bridgehead.service ..."
    systemctl enable --now bridgehead-update.timer
}

main "$@"
