#!/usr/bin/env bash
set -e
set -o pipefail

cd {{ pwd|path }}
COMPOSE_FILES="$(ls services | awk '{print " -f services/" $0}')"
[ -e ./docker-compose.override.yml ] && COMPOSE_FILES+=" -f docker-compose.override.yml"

case "$1" in
	logs)
		shift 2
		exec journalctl -u bridgehead@$PROJECT -u bridgehead-update@$PROJECT -a $@
		;;
	compose)
		shift
		exec docker compose -p bridgehead $COMPOSE_FILES $@
		;;
	update)
		docker pull samply/rusthead:latest
		exec docker run -v {{ config_dir|path }}:{{ config_dir|path }} -v {{ pwd|path }}:{{ pwd|path }} samply/rusthead:latest update
		;;
	enroll)
		do_enroll {{ beam_networks|join(" ") }}
		;;
	*)
		exit 1
		;;
esac

do_enroll() {
    # TODO
}