services:
  {{ Self::service_name() }}:
    image: docker.verbis.dkfz.de/cache/samply/focus:{{ tag }}
    environment:
      BEAM_APP_ID_LONG: {{ beam_id }}
      BEAM_PROXY_URL: {{ beam_url }}
      BLAZE_URL: {{ blaze_url }}fhir/
      API_KEY: "{{ beam_secret }}"
      RETRY_COUNT: 128
      EPSILON: 0.28
      ENDPOINT_TYPE: {{ endpoint_type }}
    {%- if let Some((exporter_url, exporter_api_key)) = exporter %}
      EXPORTER_URL: "{{ exporter_url }}"
      EXPORTER_API_KEY: "{{ exporter_api_key }}"
    {%- endif %}
