services:
  {{ Self::service_name() }}:
    image: samply/focus
    environment:
      BEAM_APP_ID_LONG: {{ beam_id }}
      BEAM_URL: {{ beam_url }}
      BLAZE_URL: {{ blaze_url }}fhir/
      API_KEY: "{{ beam_secret }}"
      RETRY_COUNT: 128
      EPSILON: 0.28
