
services:
  id-manager:
    image: docker.verbis.dkfz.de/bridgehead/magicpl
    environment:
      TOMCAT_REVERSEPROXY_FQDN: {{ hostname }}
      TOMCAT_REVERSEPROXY_SSL: "true"
      MAGICPL_SITE: {{ id }}
      MAGICPL_ALLOWED_ORIGINS: https://{{ hostname }}
      MAGICPL_LOCAL_PATIENTLIST_APIKEY: {{ local_apikey }}
      MAGICPL_CENTRAXX_APIKEY: {{ conf.upload_apikey }}
      MAGICPL_CONNECTOR_APIKEY: {{ conf.read_apikey }}
      MAGICPL_CENTRAL_PATIENTLIST_APIKEY: {{ conf.central_patientlist_apikey }}
      MAGICPL_CONTROLNUMBERGENERATOR_APIKEY: {{ conf.controlnumbergenerator_apikey }}
    depends_on:
      - patientlist
      - idm-traefik-forward-auth
    labels:
      - "traefik.enable=true"
      # Router with Authentication
      - "traefik.http.routers.id-manager.rule=PathPrefix(`/id-manager`)"
      - "traefik.http.routers.id-manager.tls=true"
      - "traefik.http.routers.id-manager.middlewares=traefik-forward-auth-idm"
      - "traefik.http.routers.id-manager.service=id-manager-service"
      # Router without Authentication
      - "traefik.http.routers.id-manager-compatibility.rule=PathPrefix(`/id-manager/paths/translator/getIds`)"
      - "traefik.http.routers.id-manager-compatibility.tls=true"
      - "traefik.http.routers.id-manager-compatibility.service=id-manager-service"
      # Definition of Service
      - "traefik.http.services.id-manager-service.loadbalancer.server.port=8080"
      - "traefik.http.services.id-manager-service.loadbalancer.server.scheme=http"

  patientlist:
    image: docker.verbis.dkfz.de/bridgehead/mainzelliste
    environment:
      - TOMCAT_REVERSEPROXY_FQDN={{ hostname }}
      - TOMCAT_REVERSEPROXY_SSL=true
      - ML_SITE={{ id }}
      - ML_DB_HOST={{ Self::pg_name() }}
      - ML_DB_PASS={{ postgres_pw }}
      - ML_API_KEY={{ local_apikey }}
      - ML_UPLOAD_API_KEY={{ conf.upload_apikey }}
      # Add Variables from /etc/patientlist-id-generators.env
      {%- for (key, seed) in conf.seeds %}
      - ML_{{ key }}_IDGENERATOR_RANDOM_1={{ seed.0 }}
      - ML_{{ key }}_IDGENERATOR_RANDOM_2={{ seed.1 }}
      - ML_{{ key }}_IDGENERATOR_RANDOM_3={{ seed.2 }}
      {%- endfor %}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.patientlist.rule=PathPrefix(`/patientlist`)"
      - "traefik.http.services.patientlist.loadbalancer.server.port=8080"
      - "traefik.http.routers.patientlist.tls=true"
    depends_on:
      - {{ Self::pg_name() }}

  idm-traefik-forward-auth:
    image: docker.verbis.dkfz.de/cache/oauth2-proxy/oauth2-proxy:latest
    environment:
      - http_proxy={{ fw_proxy_url }}
      - https_proxy={{ fw_proxy_url }}
      - OAUTH2_PROXY_PROVIDER=oidc
      - OAUTH2_PROXY_SKIP_PROVIDER_BUTTON=true
      - OAUTH2_PROXY_OIDC_ISSUER_URL={{ oidc.private_issuer_url() }}
      - OAUTH2_PROXY_CLIENT_ID={{ oidc.client_id() }}
      - OAUTH2_PROXY_CLIENT_SECRET={{ oidc.client_secret() }}
      - OAUTH2_PROXY_COOKIE_SECRET={{ conf.auth_cookie_secret }}
      - OAUTH2_PROXY_COOKIE_NAME=_BRIDGEHEAD_oauth2_idm
      - OAUTH2_PROXY_COOKIE_DOMAINS=.{{ hostname }}
      - OAUTH2_PROXY_HTTP_ADDRESS=:4180
      - OAUTH2_PROXY_REVERSE_PROXY=true
      - OAUTH2_PROXY_WHITELIST_DOMAINS=.{{ hostname }}
      - OAUTH2_PROXY_UPSTREAMS=static://202
      - OAUTH2_PROXY_EMAIL_DOMAINS=*
      - OAUTH2_PROXY_SCOPE=openid profile email
      # Pass Authorization Header and some user information to backend services
      - OAUTH2_PROXY_SET_AUTHORIZATION_HEADER=true
      - OAUTH2_PROXY_SET_XAUTHREQUEST=true
      - OAUTH2_PROXY_ALLOWED_GROUPS={{ oidc_group }}
      - OAUTH2_PROXY_OIDC_GROUPS_CLAIM=groups
      - OAUTH2_PROXY_PROXY_PREFIX=/oauth2-idm
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.idm-traefik-forward-auth.loadbalancer.server.port=4180"
      - "traefik.http.routers.traefik-forward-auth.rule=Host(`{{ hostname }}`) && PathPrefix(`/oauth2-idm`)"
      - "traefik.http.routers.traefik-forward-auth.tls=true"
      - "traefik.http.middlewares.traefik-forward-auth-idm.forwardauth.address=http://idm-traefik-forward-auth:4180"
      - "traefik.http.middlewares.traefik-forward-auth-idm.forwardauth.authResponseHeaders=Authorization"
    depends_on:
      {{ fw_proxy_name }}:
        condition: service_healthy

volumes:
  patientlist-db-data:
