{% let data_volume = Self::service_name() %}
services:
  {{ Self::service_name() }}:
    image: docker.verbis.dkfz.de/cache/postgres:15.6-alpine
    environment:
      POSTGRES_USER: {{ user }}
      POSTGRES_DB: {{ realm }}
      POSTGRES_PASSWORD: {{ password }}
    volumes:
      - "{{ data_volume }}:/var/lib/postgresql/data"

volumes:
  {{ data_volume|make_volume }}
