{% let name = Self::service_name() %}
services:
  teiler-orchestrator:
    image: docker.verbis.dkfz.de/cache/samply/teiler-orchestrator:latest
    container_name: bridgehead-teiler-orchestrator
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.teiler_orchestrator_{{ project }}.rule=PathPrefix(`/{{ name }}`)"
      - "traefik.http.services.teiler_orchestrator_{{ project }}.loadbalancer.server.port=9000"
      - "traefik.http.routers.teiler_orchestrator_{{ project }}.tls=true"
      - "traefik.http.middlewares.teiler_orchestrator_{{ project }}_strip.stripprefix.prefixes=/{{ name }}"
      - "traefik.http.routers.teiler_orchestrator_{{ project }}.middlewares=teiler_orchestrator_{{ project }}_strip"
    environment:
      TEILER_BACKEND_URL: "/{{ name }}-backend"
      TEILER_DASHBOARD_URL: "/{{ name }}-dashboard"
      DEFAULT_LANGUAGE: "{{ conf.language.to_ascii_lowercase() }}"
      HTTP_RELATIVE_PATH: "/{{ name }}"

  teiler-dashboard:
    image: docker.verbis.dkfz.de/cache/samply/teiler-dashboard:latest
    container_name: bridgehead-teiler-dashboard
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.teiler_dashboard_{{ project }}.rule=PathPrefix(`/{{ name }}-dashboard`)"
      - "traefik.http.services.teiler_dashboard_{{ project }}.loadbalancer.server.port=80"
      - "traefik.http.routers.teiler_dashboard_{{ project }}.tls=true"
      - "traefik.http.middlewares.teiler_dashboard_{{ project }}_strip.stripprefix.prefixes=/{{ name }}-dashboard"
      - "traefik.http.routers.teiler_dashboard_{{ project }}.middlewares=teiler_dashboard_{{ project }}_strip"
    environment:
      DEFAULT_LANGUAGE: "{{ conf.language }}"
      TEILER_BACKEND_URL: "/{{ name }}-backend"
      TEILER_DASHBOARD_URL: "/{{ name }}-dashboard"
      OIDC_URL: "{{ oidc_client.pub_issuer_url() }}"
      OIDC_CLIENT_ID: "{{ oidc_client.client_id() }}"
      OIDC_TOKEN_GROUP: "groups"
      TEILER_ADMIN_NAME: ""
      TEILER_ADMIN_EMAIL: ""
      TEILER_ADMIN_PHONE: ""
      TEILER_PROJECT: "{{ project }}"
      EXPORTER_API_KEY: "{{ exporter_api_key }}"
      TEILER_ORCHESTRATOR_URL: "/{{ name }}"
      TEILER_ORCHESTRATOR_HTTP_RELATIVE_PATH: "/{{ name }}"
      TEILER_USER: "{{ oidc_user_group }}"
      TEILER_ADMIN: "{{ oidc_admin_group }}"
      REPORTER_DEFAULT_TEMPLATE_ID: "{{ project }}-qb"
      EXPORTER_DEFAULT_TEMPLATE_ID: "{{ project }}"


  teiler-backend:
    image: docker.verbis.dkfz.de/ccp/dktk-teiler-backend:latest
    container_name: bridgehead-teiler-backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.teiler_backend_{{ project }}.rule=PathPrefix(`/{{ name }}-backend`)"
      - "traefik.http.services.teiler_backend_{{ project }}.loadbalancer.server.port=8085"
      - "traefik.http.routers.teiler_backend_{{ project }}.tls=true"
      - "traefik.http.middlewares.teiler_backend_{{ project }}_strip.stripprefix.prefixes=/{{ name }}-backend"
      - "traefik.http.routers.teiler_backend_{{ project }}.middlewares=teiler_backend_{{ project }}_strip"
    environment:
      LOG_LEVEL: "INFO"
      APPLICATION_PORT: "8085"
      DEFAULT_LANGUAGE: "{{ conf.language }}"
      TEILER_ORCHESTRATOR_HTTP_RELATIVE_PATH: "/{{ name }}"
      TEILER_ORCHESTRATOR_URL: "/{{ name }}"
      TEILER_DASHBOARD_DE_URL: "/{{ name }}-dashboard/de"
      TEILER_DASHBOARD_EN_URL: "/{{ name }}-dashboard/en"
      HTTP_PROXY: {{ forward_proxy_url }}
      ENABLE_MTBA: {{ mtba_enabled }}"
      ENABLE_DATASHIELD: {{ datashield_enabled }}"
      IDMANAGER_UPLOAD_APIKEY: {{ idm_upload_apikey.as_deref().unwrap_or_default() }} # Used for health checks
