services:
  transfair:
    image: docker.verbis.dkfz.de/cache/samply/transfair:latest
    environment:
      {%- if let Some(ttp) = conf.ttp %}
      - TTP_URL={{ ttp.url }}
      - TTP_AUTH={{ ttp.auth }}
      - PROJECT_ID_SYSTEM={{ ttp.project_id_system }}
      {%- match ttp.ttp_type %}
      {%- when TtpType::Greifswald with { source, epix_domain, gpas_domain } %}
      - TTP_TYPE=greifswald
      - TTP_GW_SOURCE={{ source }}
      - TTP_GW_EPIX_DOMAIN={{ epix_domain }}
      - TTP_GW_GPAS_DOMAIN={{ gpas_domain }}
      {%- when TtpType::Mainzelliste with { apikey } %}
      - TTP_TYPE=mainzelliste
      - TTP_ML_API_KEY={{ apikey }}
      {%- endmatch %}
      {%- endif %}
      {%- if let Some(server) = conf.fhir_requests %}
      - FHIR_REQUEST_URL={{ server.url }}
      - FHIR_REQUEST_CREDENTIALS={{ server.auth }}
      {%- else %}
      - FHIR_REQUEST_URL=http://bridgehead-transfair-requests-blaze:8080
      {%- endif %}
      {%- if let Some(server) = conf.fhir_input %}
      - FHIR_INPUT_URL={{ server.url }}
      - FHIR_INPUT_CREDENTIALS={{ server.auth }}
      {%- else %}
      - FHIR_INPUT_URL=http://bridgehead-transfair-input-blaze:8080
      {%- endif %}
      - FHIR_OUTPUT_URL={{ fhir_out_server.url }}
      - FHIR_OUTPUT_CREDENTIALS={{ fhir_out_server.auth }}
      - EXCHANGE_ID_SYSTEM={{ conf.exchange_id_system }}
      - DATABASE_URL=sqlite://transfair/data_requests.sql?mode=rwc
      - RUST_LOG=${RUST_LOG:-info}
      - TLS_CA_CERTIFICATES_DIR=/conf/trusted-ca-certs
      - TLS_DISABLE={{ conf.tls_disable }}
    volumes:
      - transfair-data:/transfair
      - {{ trusted_ca_certs.display() }}:/conf/trusted-ca-certs:ro

{%- if conf.fhir_input.is_none() %}
  transfair-input-blaze:
    image: docker.verbis.dkfz.de/cache/samply/blaze:latest
    container_name: bridgehead-transfair-input-blaze
    environment:
      BASE_URL: "http://bridgehead-transfair-input-blaze:8080"
      JAVA_TOOL_OPTIONS: "-Xmx1024m"
      DB_BLOCK_CACHE_SIZE: 1024
      CQL_EXPR_CACHE_SIZE: 8
      ENFORCE_REFERENTIAL_INTEGRITY: "false"
    volumes:
      - "transfair-input-blaze-data:/app/data"
{%- endif %}

{%- if conf.fhir_requests.is_none() %}
  transfair-request-blaze:
    image: docker.verbis.dkfz.de/cache/samply/blaze:latest
    container_name: bridgehead-transfair-requests-blaze
    environment:
      BASE_URL: "http://bridgehead-transfair-requests-blaze:8080"
      JAVA_TOOL_OPTIONS: "-Xmx1024m"
      DB_BLOCK_CACHE_SIZE: 1024
      CQL_EXPR_CACHE_SIZE: 8
      ENFORCE_REFERENTIAL_INTEGRITY: "false"
    volumes:
      - "transfair-request-blaze-data:/app/data"
{%- endif %}

volumes:
{%- if conf.fhir_input.is_none() %}
  transfair-input-blaze-data:
{%- endif %}
{%- if conf.fhir_requests.is_none() %}
  transfair-request-blaze-data:
{%- endif %}
  transfair-data: